name: Build on Linux

on:
  push:
    tags:
      - "v\\d+.\\d+.\\d+"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v4.0.0
      with:
        version: "5.15.2"
        host: "linux"
        target: "desktop"

    - name: Configure CMake
      run: cmake .

    - name: Build
      run: cmake --build .

    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v4
