name: Build on Windows

on:
  push:
    branches: [ "main", "windows-build" ]

env:
  BUILD_TYPE: Release

jobs:
  Build:
    runs-on: windows-2022

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v4.0.0
      with:
        version: "5.15.2"
        host: "windows"
        target: "desktop"

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -B ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ github.workspace }} --config ${{ env.BUILD_TYPE }}

    - name: Deploy
      run: |
        cd bin/${{ env.BUILD_TYPE }}
        run: windeployqt aircalc.exe

    - name: Archive built binaries
      uses: actions/upload-artifact@v4
      with:
        name: "aircalc-windows"
        path: bin/${{ env.BUILD_TYPE }}

    - name: Download built binaries
      uses: actions/download-artifact@v4
      with:
        name: "aircalc-windows"
        path: bin/${{ env.BUILD_TYPE }}
